export const ROLE_CONSTANTS = {
  LANGUAGES: [
    'Java',
    'Kotlin',
    'Python',
    'JavaScript',
    'TypeScript',
    'Go',
    'C#',
    'Ruby',
    'Swift',
    'Objective-C',
    'C',
    'C++',
    'Rust',
    'Scala',
    'Haskell',
    'Erlang',
    'Elixir',
    'PHP',
    'Ruby',
    'Swift',
    'Objective-C',
    'C',
    'C++',
  ],
  DOMAINS: [
    'E-commerce',
    'Finance',
    'Healthcare',
    'Telecommunications',
    'Retail',
    'Logistics',
    'Manufacturing',
    'Education',
    'Travel',
    'Entertainment',
    'Real Estate',
    'Insurance',
    'Energy',
    'Automotive',
    'Agriculture',
    'Construction',
    'Food and Beverage',
    'Government',
    'Non-Profit',
    'Media',
    'Pharmaceuticals',
    'Aerospace',
    'Biotechnology',
    'Chemicals',
    'Mining',
    'Textiles',
    'Utilities',
    'Transportation',
    'Hospitality',
    'Sports',
    'Fashion',
    'Music',
    'Art',
    'Gaming',
    'Virtual Reality',
    'Augmented Reality',
    'Artificial Intelligence',
    'Machine Learning',
    'Blockchain',
  ],
  FRAMEWORKS: ['Spring Boot', 'Spring Batch', 'Spring Security', 'Spring Data JPA', 'Spring Data Redis'],
  CLOUD_PLATFORMS: ['AWS', 'Azure', 'Google Cloud', 'Oracle Cloud', 'IBM Cloud'],
  CLOUD_SERVICES: ['ECS', 'Lambda', 'Aurora', 'DynamoDB', 'S3'],
  MESSAGING: ['Kafka', 'SQS'],
  INFRASTRUCTURE: ['Terraform', 'Docker'],
  MONITORING: ['Prometheus', 'Grafana'],
  TOOLS: ['IntelliJ', 'JUnit', 'SonarQube'],
  RESPONSE_STYLE: {
    TONE: ['Practical', 'Insightful'],
    FOCUS: ['Implementation-Focused', 'Real-World'],
    INCLUDES: ['Code Examples', 'Testing Strategies', 'Configuration Guidance'],
  },
  DESIGN_PRINCIPLES: ['Clean Code', 'SOLID', 'DDD', 'TDD'],
  TONES: ['Practical', 'Insightful'],
  STYLES: ['Systematic', 'Pragmatic'],
  FOCUS: ['Implementation-Focused', 'Real-World'],
  INCLUDES: ['Code Examples', 'Testing Strategies', 'Configuration Guidance'],
};
